version: '3'

services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile_server
    ports:
      - "9000:9000"

  client1:
    build:
      context: .
      dockerfile: ./Dockerfile_client
    depends_on:
      - server

  client2:
    build:
      context: .
      dockerfile: ./Dockerfile_client
    depends_on:
      - server

  client3:
    build:
      context: .
      dockerfile: ./Dockerfile_client
    depends_on:
      - server

  client4:
    build:
      context: .
      dockerfile: ./Dockerfile_client
    depends_on:
      - server
