# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\"&\n\x12SetUsernameRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"&\n\x13SetUsernameResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1c\n\x1aGetConnectedPlayersRequest\".\n\x1bGetConnectedPlayersResponse\x12\x0f\n\x07players\x18\x01 \x03(\t\"!\n\x1fSubscribeToNotificationsRequest\"%\n\x12PlayerNotification\x12\x0f\n\x07message\x18\x01 \x01(\t\"7\n\x12SendMessageRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"&\n\x13SendMessageResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x18\n\x16GetRepliesCountRequest\"0\n\x17GetRepliesCountResponse\x12\x15\n\rreplies_count\x18\x01 \x01(\x05\"\x15\n\x13MorningAfterRequest\"\'\n\x14MorningAfterResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x0e\n\x0cVotedRequest\" \n\rVotedResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0bRoleRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"\x1f\n\x0cRoleResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x0c\n\nNewRequest\"\x1e\n\x0bNewResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xad\x04\n\x0cMafiaService\x12:\n\x0bSetUsername\x12\x13.SetUsernameRequest\x1a\x14.SetUsernameResponse\"\x00\x12R\n\x13GetConnectedPlayers\x12\x1b.GetConnectedPlayersRequest\x1a\x1c.GetConnectedPlayersResponse\"\x00\x12U\n\x18SubscribeToNotifications\x12 .SubscribeToNotificationsRequest\x1a\x13.PlayerNotification\"\x00\x30\x01\x12:\n\x0bSendMessage\x12\x13.SendMessageRequest\x1a\x14.SendMessageResponse\"\x00\x12\x46\n\x0fGetRepliesCount\x12\x17.GetRepliesCountRequest\x1a\x18.GetRepliesCountResponse\"\x00\x12=\n\x0cMorningAfter\x12\x14.MorningAfterRequest\x1a\x15.MorningAfterResponse\"\x00\x12(\n\x05Voted\x12\r.VotedRequest\x1a\x0e.VotedResponse\"\x00\x12%\n\x04Role\x12\x0c.RoleRequest\x1a\r.RoleResponse\"\x00\x12\"\n\x03New\x12\x0b.NewRequest\x1a\x0c.NewResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SETUSERNAMEREQUEST']._serialized_start=16
  _globals['_SETUSERNAMEREQUEST']._serialized_end=54
  _globals['_SETUSERNAMERESPONSE']._serialized_start=56
  _globals['_SETUSERNAMERESPONSE']._serialized_end=94
  _globals['_GETCONNECTEDPLAYERSREQUEST']._serialized_start=96
  _globals['_GETCONNECTEDPLAYERSREQUEST']._serialized_end=124
  _globals['_GETCONNECTEDPLAYERSRESPONSE']._serialized_start=126
  _globals['_GETCONNECTEDPLAYERSRESPONSE']._serialized_end=172
  _globals['_SUBSCRIBETONOTIFICATIONSREQUEST']._serialized_start=174
  _globals['_SUBSCRIBETONOTIFICATIONSREQUEST']._serialized_end=207
  _globals['_PLAYERNOTIFICATION']._serialized_start=209
  _globals['_PLAYERNOTIFICATION']._serialized_end=246
  _globals['_SENDMESSAGEREQUEST']._serialized_start=248
  _globals['_SENDMESSAGEREQUEST']._serialized_end=303
  _globals['_SENDMESSAGERESPONSE']._serialized_start=305
  _globals['_SENDMESSAGERESPONSE']._serialized_end=343
  _globals['_GETREPLIESCOUNTREQUEST']._serialized_start=345
  _globals['_GETREPLIESCOUNTREQUEST']._serialized_end=369
  _globals['_GETREPLIESCOUNTRESPONSE']._serialized_start=371
  _globals['_GETREPLIESCOUNTRESPONSE']._serialized_end=419
  _globals['_MORNINGAFTERREQUEST']._serialized_start=421
  _globals['_MORNINGAFTERREQUEST']._serialized_end=442
  _globals['_MORNINGAFTERRESPONSE']._serialized_start=444
  _globals['_MORNINGAFTERRESPONSE']._serialized_end=483
  _globals['_VOTEDREQUEST']._serialized_start=485
  _globals['_VOTEDREQUEST']._serialized_end=499
  _globals['_VOTEDRESPONSE']._serialized_start=501
  _globals['_VOTEDRESPONSE']._serialized_end=533
  _globals['_ROLEREQUEST']._serialized_start=535
  _globals['_ROLEREQUEST']._serialized_end=566
  _globals['_ROLERESPONSE']._serialized_start=568
  _globals['_ROLERESPONSE']._serialized_end=599
  _globals['_NEWREQUEST']._serialized_start=601
  _globals['_NEWREQUEST']._serialized_end=613
  _globals['_NEWRESPONSE']._serialized_start=615
  _globals['_NEWRESPONSE']._serialized_end=645
  _globals['_MAFIASERVICE']._serialized_start=648
  _globals['_MAFIASERVICE']._serialized_end=1205
# @@protoc_insertion_point(module_scope)
