# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\"&\n\x12SetUsernameRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"&\n\x13SetUsernameResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0bQuitRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"\x1f\n\x0cQuitResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1c\n\x1aGetConnectedPlayersRequest\".\n\x1bGetConnectedPlayersResponse\x12\x0f\n\x07players\x18\x01 \x03(\t\"!\n\x1fSubscribeToNotificationsRequest\"%\n\x12PlayerNotification\x12\x0f\n\x07message\x18\x01 \x01(\t2\xa0\x02\n\x0cMafiaService\x12:\n\x0bSetUsername\x12\x13.SetUsernameRequest\x1a\x14.SetUsernameResponse\"\x00\x12)\n\x08QuitGame\x12\x0c.QuitRequest\x1a\r.QuitResponse\"\x00\x12R\n\x13GetConnectedPlayers\x12\x1b.GetConnectedPlayersRequest\x1a\x1c.GetConnectedPlayersResponse\"\x00\x12U\n\x18SubscribeToNotifications\x12 .SubscribeToNotificationsRequest\x1a\x13.PlayerNotification\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SETUSERNAMEREQUEST._serialized_start=16
  _SETUSERNAMEREQUEST._serialized_end=54
  _SETUSERNAMERESPONSE._serialized_start=56
  _SETUSERNAMERESPONSE._serialized_end=94
  _QUITREQUEST._serialized_start=96
  _QUITREQUEST._serialized_end=127
  _QUITRESPONSE._serialized_start=129
  _QUITRESPONSE._serialized_end=160
  _GETCONNECTEDPLAYERSREQUEST._serialized_start=162
  _GETCONNECTEDPLAYERSREQUEST._serialized_end=190
  _GETCONNECTEDPLAYERSRESPONSE._serialized_start=192
  _GETCONNECTEDPLAYERSRESPONSE._serialized_end=238
  _SUBSCRIBETONOTIFICATIONSREQUEST._serialized_start=240
  _SUBSCRIBETONOTIFICATIONSREQUEST._serialized_end=273
  _PLAYERNOTIFICATION._serialized_start=275
  _PLAYERNOTIFICATION._serialized_end=312
  _MAFIASERVICE._serialized_start=315
  _MAFIASERVICE._serialized_end=603
# @@protoc_insertion_point(module_scope)
