# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import server_pb2 as server__pb2


class MafiaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetUsername = channel.unary_unary(
                '/MafiaService/SetUsername',
                request_serializer=server__pb2.SetUsernameRequest.SerializeToString,
                response_deserializer=server__pb2.SetUsernameResponse.FromString,
                )
        self.QuitGame = channel.unary_unary(
                '/MafiaService/QuitGame',
                request_serializer=server__pb2.QuitRequest.SerializeToString,
                response_deserializer=server__pb2.QuitResponse.FromString,
                )
        self.GetConnectedPlayers = channel.unary_unary(
                '/MafiaService/GetConnectedPlayers',
                request_serializer=server__pb2.GetConnectedPlayersRequest.SerializeToString,
                response_deserializer=server__pb2.GetConnectedPlayersResponse.FromString,
                )
        self.SubscribeToNotifications = channel.unary_stream(
                '/MafiaService/SubscribeToNotifications',
                request_serializer=server__pb2.SubscribeToNotificationsRequest.SerializeToString,
                response_deserializer=server__pb2.PlayerNotification.FromString,
                )


class MafiaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetUsername(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QuitGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConnectedPlayers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeToNotifications(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MafiaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetUsername': grpc.unary_unary_rpc_method_handler(
                    servicer.SetUsername,
                    request_deserializer=server__pb2.SetUsernameRequest.FromString,
                    response_serializer=server__pb2.SetUsernameResponse.SerializeToString,
            ),
            'QuitGame': grpc.unary_unary_rpc_method_handler(
                    servicer.QuitGame,
                    request_deserializer=server__pb2.QuitRequest.FromString,
                    response_serializer=server__pb2.QuitResponse.SerializeToString,
            ),
            'GetConnectedPlayers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConnectedPlayers,
                    request_deserializer=server__pb2.GetConnectedPlayersRequest.FromString,
                    response_serializer=server__pb2.GetConnectedPlayersResponse.SerializeToString,
            ),
            'SubscribeToNotifications': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeToNotifications,
                    request_deserializer=server__pb2.SubscribeToNotificationsRequest.FromString,
                    response_serializer=server__pb2.PlayerNotification.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MafiaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MafiaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetUsername(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MafiaService/SetUsername',
            server__pb2.SetUsernameRequest.SerializeToString,
            server__pb2.SetUsernameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QuitGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MafiaService/QuitGame',
            server__pb2.QuitRequest.SerializeToString,
            server__pb2.QuitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetConnectedPlayers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MafiaService/GetConnectedPlayers',
            server__pb2.GetConnectedPlayersRequest.SerializeToString,
            server__pb2.GetConnectedPlayersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubscribeToNotifications(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/MafiaService/SubscribeToNotifications',
            server__pb2.SubscribeToNotificationsRequest.SerializeToString,
            server__pb2.PlayerNotification.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
